### PR TITLE
Consider useCallback result different unless the dependencies are absent or deep equal

### LINKED ISSUE #46: "different functions with the same name", but I'm using useCallback.
I've tried posting this on StackOverflow with no response was hoping to get some more detail here.  I recreated a very simple project to replicate what's going on in a bigger project of mine.  https://github.com/DaleSalcedo/PropFunctionProblem.  In my App.js I'm passing down this function:

```
const modifyPlayer = React.useCallback((playerId, propertyName, value) => {
    const playerCopy = {...playerDict[playerId]};
    playerCopy[propertyName] = value;
    const playerDictCopy = {
      ...playerDict,
      [playerId]: playerCopy
    };
    setPlayerDict(playerDictCopy);  // useState function
  }
  ,[playerDict]);
```

I pass that down 2 components as props and use it here:

```
export const Player = ({player, modifyPlayer}) => {
  const handleOnChange = React.useCallback((event) => {
    modifyPlayer(player.id, event.target.name, event.target.value);
  }, [player, modifyPlayer]);

  return (
    <div>
      <input type={"text"} name={"firstName"} value={player.firstName} onChange={handleOnChange}/>
      <input type={"text"} name={"lastName"} value={player.lastName} onChange={handleOnChange}/>
    </div>
  );
};
```

I'm not sure why it's giving me that message "different functions with the same name" for "modifyPlayer" function when I used "useCallback".

Is this a bug or can someone explain what's going on?

### PR DESCRIPTION
**Pull request by Hypnosphi**
Fixes #46 

This also applies to cases when `useMemo` returns a function

### CODE REVIEW

**Comment by vzaidman** [comment]
This part of the library is super confusing.
Since of the well known bug on react (https://github.com/facebook/react/issues/14099) we are only left with bad options:
* to notify the user about potentially frequent changes due to deps changes, but to not really offer great alternatives (turn the component into class or use the `useEventCallback` type of hooks) like it is now
* ignore changes due to changed deps like you did

i was leaning towards the first one because if you make a component pure, you probably want to know that it's being invalidated too often.
also because it's less code and complexity in the library which is relatively complex anyway.
also because i want to believe facebook will solve the issue in the near future :)

why do you think it's a good solution?

**Comment by vzaidman** [comment]
And thank you very much for the contributions!
I really appreciate it!

**Comment by Hypnosphi** [comment]
First option (current behavior) makes it impossible to use WDYR with render props pattern

**Comment by Hypnosphi** [comment]
> notify the user about potentially frequent changes

Any change (props, hooks etc) is potentially frequent. I see the main goal of WDYR in detecting deep equalities

**Comment by Hypnosphi** [comment]
I don't see how this

```
const callback = useCallback(() => value, [value])

return <Component callback={callback} />
```

is much different from that
```
const object = useMemo(() => ({value}), [value])

return <Component object={object} />
```

WDYR will complain about the first one, but not about the second one

**Comment by vzaidman** [comment]
Thanks!
I reviewed it late at night and didn't appreciate how great this solution is at first!!!

**Comment by vzaidman** [comment]
published as `v5.0.0-alpha.2`

**Comment by vzaidman** [comment]
fixed #46

**Pull request merged**
